services:
    zabbix-postgresql:
        image: postgres:15.4
        container_name: zabbix-postgresql
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            TZ: Europe/Budapest
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USERNAME}"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./zabbix/postgres/data:/var/lib/postgresql/data
            - ./zabbix/postgres/postgresql.conf:/var/lib/postgresql/postgresql.conf
            - ./zabbix/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        command: postgres -c config_file=/var/lib/postgresql/postgresql.conf
        restart: unless-stopped
        networks:
            - monitoring
    zabbix-server:
      image: zabbix/zabbix-server-pgsql:ubuntu-latest
      container_name: zabbix-server
      restart: unless-stopped
      environment:   # The Postgres database value variable
        DB_SERVER_HOST: zabbix-postgresql
        POSTGRES_USER: zabbix
        POSTGRES_PASSWORD: zabbix
        POSTGRES_DB: zabbix
        ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
        ZBX_DEBUGLEVEL: 1
        ZBX_HOUSEKEEPINGFREQUENCY: 1
        ZBX_MAXHOUSEKEEPERDELETE: 5000
      depends_on:
          zabbix-postgresql:
              condition: service_healthy
      volumes:
        - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      networks:
        - monitoring
    
    zabbix-web:    # The main Zabbix web UI or interface 
      image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
      container_name: zabbix-web
      restart: unless-stopped
      environment:  
        DB_SERVER_HOST: zabbix-postgresql
        POSTGRES_USER: zabbix
        POSTGRES_PASSWORD: zabbix
        POSTGRES_DB: zabbix
        ZBX_SERVER_HOST: zabbix-server
        ZBX_POSTMAXSIZE: 64M
        ZBX_MAXEXECUTIONTIME: 500
      depends_on:
        zabbix-server:
          condition: service_started
        zabbix-postgresql:
          condition: service_healthy
      ports:    # Port where Zabbix UI is available
        - 8090:8080
      networks:
        - monitoring
    zabbix-agent:   
      image: zabbix/zabbix-agent2:ubuntu-latest
      container_name: zabbix-agent
      privileged: true
      restart: unless-stopped
      environment:
        ZBX_HOSTNAME: zabbix-agent
        ZBX_SERVER_HOST: zabbix-server
        ZBX_DEBUGLEVEL: 5
      volumes:
        - ./zabbix/postgresql.conf:/etc/zabbix/zabbix_agent2.d/plugins.d/postgresql.conf
        - ./zabbix/zabbix_agent2.conf:/etc/zabbix/zabbix_agent2.conf
      networks:
        - monitoring

networks:
    monitoring:
        driver: bridge
